### ISSUE TITLE
It seems that the link of training set is just the original Open-X Dataset.

### ISSUE THREAD

**Issue by Icecream-blue-sky** [Dantong88/Gripper_detector#1]
![image](https://github.com/user-attachments/assets/7f9abc2b-b3fa-4434-88fe-48422eef0c13)

**Comment by Dantong88** [comment]
yes, we delete the link to prevent further confusion. The trianing set is sub-sampled images from OXE and bbox annotations, we might release it later.

**Comment by SiyuanHuang95** [comment]
Can you provide more detailed information about the Bbox annotations, e.g. how do u get these annotations and how many frames are you used for the detector training @Dantong88
